
import { ServiceCategory, StreamingService } from './types';

const TRAILER_1 = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
const MOVIE_1 = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4';
const TRAILER_2 = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4';
const MOVIE_2 = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4';

export const STREAMING_SERVICES: StreamingService[] = [
  {
    id: 'prime-action',
    name: 'Neon Velocity',
    brand: 'aimefilms',
    category: ServiceCategory.GENERAL,
    description: 'A high-stakes chase through a futuristic megalopolis.',
    synopsis: 'A former street racer must deliver a mysterious package across the city while being hunted by a rogue military unit.',
    highlights: ['Action', 'Thriller / Suspense', 'Science Fiction (Sci-Fi)'],
    pros: ['4K HDR', 'Dolby Atmos'],
    imageUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=1200',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Amazon_Prime_Video_logo.svg',
    link: 'https://www.primevideo.com',
    videoUrl: TRAILER_1,
    fullMovieUrl: MOVIE_1,
    rating: '9.2',
    year: '2024',
    duration: '2h 15m',
    cast: ['Karl Urban', 'Antony Starr'],
    genre: ['Action', 'Science Fiction (Sci-Fi)', 'Thriller / Suspense', 'War / Military', 'Crime'],
    matchScore: 98,
    isTrending: true,
    section: 'english',
    price: 'Free with Prime'
  },
  {
    id: 'hbo-drama',
    name: 'The Last Dynasty',
    brand: 'tntfilms',
    category: ServiceCategory.GENERAL,
    description: 'An epic tale of power, betrayal, and history.',
    synopsis: 'In the heart of the 18th century, a young heir must navigate the treacherous waters of the royal court to save their legacy.',
    highlights: ['Drama', 'Biography / Historical', 'Romance'],
    pros: ['Award Winning', 'Exclusive'],
    imageUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=1200',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/17/HBO_Max_Logo.svg',
    link: 'https://www.max.com',
    videoUrl: TRAILER_2,
    fullMovieUrl: MOVIE_2,
    rating: '9.5',
    year: '2024',
    duration: '1h 58m',
    cast: ['Colin Farrell', 'Pedro Pascal'],
    genre: ['Drama', 'Biography / Historical', 'Romance', 'War / Military', 'Mystery'],
    matchScore: 99,
    isTrending: true,
    isNew: true,
    section: 'kinyarwanda',
    price: '$4.99 Rent'
  },
  {
    id: 'disney-adventure',
    name: 'Cloud Runner',
    brand: 'princefilms',
    category: ServiceCategory.GENERAL,
    description: 'A magical journey for the whole family.',
    synopsis: 'A young girl discovers a hidden world in the clouds where mythical creatures live and magic is real.',
    highlights: ['Animation', 'Adventure', 'Fantasy'],
    pros: ['Family / Kids', 'Magic'],
    imageUrl: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?auto=format&fit=crop&q=80&w=1200',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Disney_plus_logo.svg',
    link: 'https://www.disneyplus.com',
    videoUrl: TRAILER_1,
    fullMovieUrl: MOVIE_1,
    rating: '8.8',
    year: '2024',
    duration: '1h 45m',
    cast: ['Ryan Reynolds', 'Tom Hiddleston'],
    genre: ['Animation', 'Adventure', 'Fantasy', 'Family / Kids', 'Musical / Music'],
    matchScore: 94,
    isNew: true,
    section: 'rwanda',
    price: 'Included'
  },
  {
    id: 'crunchy-anime',
    name: 'Spirit Blade',
    brand: 'aimefilms',
    category: ServiceCategory.NICHE,
    description: 'The ultimate sword-fighting anime experience.',
    synopsis: 'A samurai with a cursed blade seeks redemption in a land filled with demons and spirits.',
    highlights: ['Animation', 'Action', 'Fantasy'],
    pros: ['Simulcast', 'Uncut'],
    imageUrl: 'https://images.unsplash.com/photo-1578632292335-df3abbb0d586?auto=format&fit=crop&q=80&w=1200',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Crunchyroll_Logo.svg',
    link: 'https://www.crunchyroll.com',
    videoUrl: TRAILER_2,
    fullMovieUrl: MOVIE_2,
    rating: '8.7',
    year: '2024',
    duration: '24m',
    cast: ['Mayumi Tanaka'],
    genre: ['Animation', 'Action', 'Fantasy', 'Adventure', 'Short Films'],
    matchScore: 91,
    isTrending: true,
    section: 'kinyarwanda',
    price: 'Free Ad-Supported'
  }
];
